"""add otp consumed_at for idempotent verify

AAD-QUAL-027: stripped the unreviewed "### commands auto generated by
Alembic - please adjust! ###" markers left over from `alembic revision
--autogenerate` — nobody had actually adjusted anything here, so the
markers were just noise. The finding's other ask — dropping
`otp_challenges` once the OTP subsystem it belonged to was fully removed —
turned out to already be done: 0010_refresh_tokens.py drops this same
table (see its "drop dead otp_challenges" section), as a direct
consequence of AAD-QUAL-001's own migration. Nothing further to do there.

Revision ID: 0002_otp_grace
Revises: 0001_initial
Create Date: 2026-08-07 05:12:45.357036
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002_otp_grace'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('otp_challenges', sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('otp_challenges', 'consumed_at')
