"""add otp consumed_at for idempotent verify

Revision ID: c2de01ed04d6
Revises: 0001_initial
Create Date: 2026-08-07 05:12:45.357036
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002_otp_grace'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_challenges', sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_challenges', 'consumed_at')
    # ### end Alembic commands ###
